name = "QuantumFockDynamics"
uuid = "b136d4ac-0281-4efb-a313-ed4bf251d6d6"
version = "1.0.0-DEV"
authors = ["Louis Lammertyn"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
QuantumFockCore = "c4c52a10-75be-47fa-9298-4f0d724bc661"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
Combinatorics = "1.0.3"
DifferentialEquations = "7.16.1"
LinearAlgebra = "1.12.0"
OrdinaryDiffEq = "6.102.1"
SparseArrayKit = "0.4.1"
TensorOperations = "5.3.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
