name = "QuantumFockDynamics"
uuid = "b136d4ac-0281-4efb-a313-ed4bf251d6d6"
authors = ["Louis Lammertyn"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
